name: Docker Image CI

on:
  push:
#    paths:
#      - 'Dockerfile'

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: Push docker image
      uses: actions/docker/login@master
      secrets: ["DOCKER_USERNAME", "DOCKER_PASSWORD"]
      run: |
        docker login
        docker push my-image-name:$(date +%s)
