name: Docker Image CI

on:
  push:
#    paths:
#      - 'Dockerfile'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag greefine/my-image:$GITHUB_SHA
      - name: Login docker
        uses: actions/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push docker image
        run: |
          docker push greefine/my-image:$GITHUB_SHA
